### ISSUE TITLE
Mint-X Window Borders

### ISSUE THREAD

**Issue by callagg2** [linuxmint/mint-themes#142]
This "issue", if i may call it that, it might be be design, anyway, within Themes,
Select Desktop => Mint-Y-Dark
Select Controls => Mint-Y-Dark
Select Window Borders => Mint-X

Now, the active window title bar is black - when in my opinion it should be grey.
Why, because, go back and change Window Borders => Mint-Y, and you see the title bar turns grey
The Title bar should only be black if you select Window Borders = Mint-Y-Dark.

This issue is present on LM19 Cinnamon and LMDE3

**Comment by JosephMcc** [comment]
You're right this is by design. The gtk theme feeds the window border theme it's colors. Many apps support a "dark theme" variant that allows just those specific apps to use the dark version of the theme. Mint-Y-Darker currently supports this. The intention is for Mint-Y to support it. The only reason it wasn't shipped that way in Mint19 was because Mate didn't properly handle it.
