### ISSUE TITLE
Chrome buttons are to close and low quality.

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-themes#186]
Firefox:
![image](https://user-images.githubusercontent.com/9551316/53294753-a35a3e80-37cb-11e9-9fb5-df4f427e0581.png)

Chrome:
![image](https://user-images.githubusercontent.com/9551316/53294759-b2d98780-37cb-11e9-840a-86d4d8a4ebff.png)

**Comment by JosephMcc** [comment]
I'm not sure how much control we have over this in the theme. Can you show a theme that does this better?

**Comment by talesaraujo** [comment]
The original Arc Theme does it quite fine:

**Arc**
![arc](https://user-images.githubusercontent.com/23703961/76676465-87763600-65a2-11ea-93db-f00af701130b.png)

**Mint Y**
![mint-y](https://user-images.githubusercontent.com/23703961/76676470-9826ac00-65a2-11ea-8186-a08bc24bd6f3.png)

For obvious reasons, the Mint Y variants also inherit this issue. Since next release relates to theme improvements, it would be great if this were fixed.

**Comment by JosephMcc** [comment]
Checked this in the latest Chrome and it seems fine.
