### ISSUE TITLE
Review the logo

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-themes#201]
As part of the website redesign, the logo is also being looked at.

**Comment by matigous** [comment]
Hello! Could you please consider this logo?
![mint-logo](https://user-images.githubusercontent.com/37050275/55371670-645b8f00-54d5-11e9-9f0a-720d75bffa79.png)

**Comment by meetdilip** [comment]
@clefebvre Where can we review the logos ? I am sure the contribution has been great.

**Comment by Gabriel38g** [comment]
You don't have to make a round logo. You should just round off the edges. like this
![logo-example](https://user-images.githubusercontent.com/30500293/55523018-5c2a5d80-5655-11e9-8326-43ddcc8c7188.png)

**Comment by isylumn** [comment]
If this is a logo contest, here's my entry!

![industrial-mint](https://user-images.githubusercontent.com/47835635/55530054-33a46280-5659-11e9-99a8-61ba01f7e61d.png)

**Comment by clefebvre** [comment]
Hi guys,

This isn't a logo contest, but I guess it always help. This issue isn't really documented yet, it's there as part of the milestone to make sure we'll be working on it prior to release.

**Comment by smartsphere** [comment]
> You don't have to make a round logo. You should just round off the edges. like this
> ![logo-example](https://user-images.githubusercontent.com/30500293/55523018-5c2a5d80-5655-11e9-8326-43ddcc8c7188.png)

I like this logo because the bottom part looks like a happy smile!
Dennis

**Comment by SebastJava** [comment]
I am still working on this...
I am not ready yet...
I am struggling to find the right green color!!?
Preview:
![LM-logo-Y-1line-03-colors](https://user-images.githubusercontent.com/31940713/55677919-e6292f00-58be-11e9-8879-d6847e6c7d9e.png)

**Comment by SebastJava** [comment]
P.S.: This is my preferred version, but i will also ship another one with the linked letters, when ready...

**Comment by smartsphere** [comment]
I like them all but forced to pick a preference would say
I like the bottom pair

I find the top too much black & green)

Dennis    ( keep up the good work)

**Comment by chadalen** [comment]
Saw this on Reddit. Simple, clean and looks like a mint leaf. In my opinion this resembles Linux Mint very well while keeping it simple. https://www.reddit.com/r/linuxmint/comments/baieww/made_a_quick_mint_logo_to_spend_some_time_i_know/?utm_medium=android_app&utm_source=share

**Comment by 2LEPRECHAUN** [comment]
Here is a suggestion not to remove the stem from the logo. I think removing the stem would be a very negative change since the leaf is already so characteristic in the shape of the logo. I use the same logo in an application on a simple home page.

![Logo](https://i.imgur.com/wI4bOAR.jpg)
![Site](https://i.imgur.com/Li4br33.jpg)

**Comment by chadalen** [comment]
@2LEPRECHAUN  top one looks great. I really like the stem.

**Comment by smartsphere** [comment]
I saw a mention of an animation ( You could have the leaf opening up /
revealing the Mint logo)
Love this version of the logo looks like a mint leaf  (cool)
Dennis

**Comment by dauntless360** [comment]
I think the problem with a circle logo is that circles are generic and don't say much by themselves. If I knew nothing about Linux Mint and looked at a circle with an L & M in it it wouldn’t mean anything to me. The same applies for a generic square, rectangle, or any other quadrilateral shapes.
 
Ubuntu has a circle logo and it works because Ubuntu has 3 people holding hands in a circle to symbolize friendship. The circle in their case puts emphasis on the image of friendship and being all connected.
 
A logo is a symbol that identifies a product. They generally shouldn't be changed once established unless the goal is to change the identity of the product.
 
The leaf should be kept in some shape or form because it symbolizes a mint leaf which I assume is what the distribution is named after for its freshness. Getting rid of it would make Mint loose the identity that it established.
 
In my opinion there is nothing wrong with stylizing an old design to reinvigorate new freshness. Thus, the new logo would benefit from a new style of leaf design and not a generic circle.

**Comment by bjd-pfq** [comment]
The current Mint logo needs to change to something entirely different.

Ever since the fall of 2016, it reminds me too much of someone. That someone is the current US president, depicted `en profil'.

In other words, it's Trump, sideways.

**Comment by usolmz** [comment]
logo draft ( CC0 )
» https://send.firefox.com/download/17d2be0ea031fe3a/#JPEN2jNWY93Wpt6LKvbmtQ

**Comment by dimasnirwan** [comment]
Hello there,
Here's my suggestion the new logo for LinuxMint.

![linuxmint-new-logo2](https://user-images.githubusercontent.com/51951178/60154066-70bf6180-9810-11e9-956a-87faaf29f6ff.png)

![linuxmint-new-logo1](https://user-images.githubusercontent.com/51951178/60154075-79179c80-9810-11e9-95a7-62e3253c25f6.png)

![linuxmint-new-logo3](https://user-images.githubusercontent.com/51951178/60154078-7d43ba00-9810-11e9-9404-91e9a3711472.png)

**Comment by dauntless360** [comment]
> The current Mint logo needs to change to something entirely different.
> 
> Ever since the fall of 2016, it reminds me too much of someone. That someone is the current US president, depicted `en profil'.
> 
> In other words, it's Trump, sideways.

I don't think USA politics should have any influence or be a deciding factor with the new logo design. You need help if you see trump when ever you look at the mint logo and this forum isn't the right place for that.

**Comment by bjd-pfq** [comment]
@dauntless360  I think you are the one that needs a bit of socialization.

Moderators: please remove that insulting post!

**Comment by usolmz** [comment]
@2LEPRECHAUN you must continue working on the logo .

**Comment by 2LEPRECHAUN** [comment]
@usolmz improving the logo redesign you say?
