### ISSUE TITLE
Review color variations

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-themes#204]
- Yellow is missing.
- Colors were inherited from Mint-X and never really reviewed (is that the best red we can come up with? No, it's just the one we already had..)
- Colors don't always match between GTK and icon themes.
- Fix folder-color-chooser to work with newly introduced "Dark" icon themes.
- Consider shipping a customization/generation tool.

**Comment by SebastJava** [comment]
I am working on this... More info on: https://linuxmintdesignteam.slack.com

**Comment by SebastJava** [comment]
Maybe I'll finish this job, eventually... Here is what i did, so far. If you want to build a test Mint-Y theme with those colors, please do so. Let me know if you are working on this, so i can just relax.

Clem and I prefer column B. I guess you should forget the green 1, 2 and 3. I would choose: Mint 2, Pink 2, and Brown 2.

I said Clem prefers column B, but that's at first glance. We need a "Mint-Y test" to really appreciate and judge...

Just use Gpick or some similar tool to pick up the color values... Thanks!

![01-Mint-Y-New-Accent-Colors-06](https://user-images.githubusercontent.com/31940713/57172261-a9802300-6deb-11e9-80a3-955e82d64b38.png)

**Comment by SebastJava** [comment]
I am still on Linux Mint 18.3 Sylvia Mate 32-bit... So i am still on GTK 3.18.9-1ubuntu3.3...

I tried to install this updated Mint-Y theme from here but it just doesn't work with my current GTK. This means i can't test these new colors. Maybe later.

**Comment by message** [comment]
I prefer column A. Switched from Ubuntu 19.10 because it turn into utter mess. Enjoining Mint, but  I miss good vibrant themes.

**Comment by SebastJava** [comment]
Okay... I should be able to work on this soon... I am now on Linux Mint Cinnamon 19.3 64 bit...

**Comment by JosephMcc** [comment]
Keep us posted on what you are working on so we can give feedback. Realistically, Column D is probably the best. A lot of work has been done to improve contrast and readability. And we need good contrast between text and background on selected items. It's not just about the prettiest. It also needs to be comfortable to use all day.

**Comment by JosephMcc** [comment]
I also have the original sources for the folder icons. I will try to get these set up in a usable way and push them up to github soon. I should have had it done already.

**Comment by SebastJava** [comment]
@JosephMcc 
There is no hurry. I am still not finished on moving to my newly acquired second hand computer. I still have to move all my data, search for a compact layout (~12 inches wide) French Canadian keyboard, configure the music player so i don't get distracted by the neighbours, etc. I should be all set in a few days. I will put my wallpapers project aside and make this Mint-Y new colours my top priority.

Colours are somewhat subjective but i will try to wrap this project into some scientific, legitimate coating. :) For example, i start by setting the colours in their purest form, using the RGB fields: red = rgb(255,0,0), orange = rgb(255,128,0), etc. Then i switch to HSL fields and i lower the saturation levels. Et cætera. And at the end i open my colour table in Pix and convert to grayscale. Pix converts the different colour weights into different grayscale levels. This way i can focus on the contrasts only. Pix does this better than GIMP, in my opinion. Just to say that i do care about improving contrast and readability. But on the other hand, i don't want to make the orange look like brown, for example.

But on top of this, i feel i have done too much talking and not much doing. So i think i won't give much news until i come up with a pack of folders ready to be installed in /usr/share/themes. I have done this before, the right way: editing the sass files and running the test script.

**Comment by SebastJava** [comment]
@JosephMcc 
I am talking about a pack of folders ready to be installed in /usr/share/themes, because, as Clement said before, there is no better way to appreciate these colours than by using it on a daily basis. A "Mint-Y-2" theme just for testing, in other words. And also, i am embarrassed to say this, but there could be a 99th revision of this colour table before moving on and making this test theme. And so the folder icons would come after that. No need to hurry.

**Comment by SebastJava** [comment]
@JosephMcc 
I have totally restarted those Mint-Y-Colors from column zero. I wanted to make this color palette using a solid and rigorous working method. This method can be quickly summarized as follow:

1. In the first step, i get the hues and lightness for the basic, pure elementary colors. Following the predefined Mint-Y color names. Most of these hues and lightness are made up of simple fractions or whole numbers. Some are composed directly in RGB mode. And some others are imported from Wikipedia.

2. In the second step, the saturation levels are being slightly lowered for most colors. This makes the colors a little less vibrant.

3. Third step and additional experiments:
In the next columns, every background color will be checked with some WCAG color contrast tools, with a white text foreground. When the calculated color contrast is insufficient, lightness and/or saturation values will be lowered as necessary. The minimum required color contrast ratio is 3:1. This "minimum" is already very constraining... For higher accessibility, there is already some high contrast themes available.

Sorry, i am not posting the new images here. Because it is still not ready, and, most of all, because we are already working on this in the LMDT on Slack.com...

P.S.: I should try to find the right balance. Dmitry Polovka prefers column A. JosephMcc said it would be better with column D. Clem said it could be column B, at first glance. And the WCAG applications are saying those green hues need to be darkened.

**Comment by SebastJava** [comment]
Here is my latest new colour palette, after lots of re-edits. I am also working on other colour related stuff, and so i will possibly make a Mint-Y-theme fork, so you can get to see the small differences in a few files. We will see this later. For now i still have to work locally, on my HDD.

![Mint-Y-Colors-40](https://user-images.githubusercontent.com/31940713/73886452-a7923700-4837-11ea-86db-6e068afa5227.png)

**Comment by SebastJava** [comment]
Columns 0, 1 and 2 are just the first steps. The actual “final product” is column 1a or 2a. I think i prefer column 1a. I did not receive much feedback so far, so i will try to make a complete Mint-Y set with this column 1a, and see how it is received...

**Comment by JosephMcc** [comment]
Closing this for now. We went through the process and ended up going with the colors we have. We can always review the individual colors going forward.
