### ISSUE TITLE
Window borders 'Mint-X' + Controls 'Mint-Y-Dark' = almost illegible titlebar text (in multiple applications)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#279]
Screenshot - in which see especially (if you can!) the titlebar text.

![image](https://user-images.githubusercontent.com/47056543/85187648-89ebd880-b2d3-11ea-832b-b64a4b737a08.png)

Testing on Mint 19.3 and Mint 20 beta, both using Cinnamon.

**Comment by mtwebster** [comment]
These pieces aren't meant to be mixed.  They're only separate entities for historical reasons and the effort to integrate them isn't worth it (enter.. client-decorated windows).

Would you file a bug with the maintainer of SuperAwesome Clear Theme because its window borders don't go well with CraigsBlackGothicWin98's gtk theme?
