### ISSUE TITLE
Firefox without titlebar looks really bad due to rounden corners

### ISSUE THREAD

**Issue by okaestne** [linuxmint/mint-themes#335]
The rounded corners introduced in 8f7ef21c956357c3a0a54ce78bf9a242a7528f33 look quite nice in most applications, but in Firefox and Thunderbird, both with titlebar disabled, they just looks completely glitched:

Firefox:
![image](https://user-images.githubusercontent.com/13122119/145315724-da976335-8351-4865-89d4-ed8531e7ce7e.png)
Thunderbird
![image](https://user-images.githubusercontent.com/13122119/145316284-2a94a809-1ed4-49f6-ab78-9ac0013d4234.png)

It looks like it has a rectangular outer border and a doubled rounded inner border. Also the icons to maximize and minimize look different; the close icon is cut off on the top and bottom.

Can't tell whether this is fixable by the theme or only by Mozilla, but in any case it looks unacceptable bad.

Addtional note: I can reproduce this in a fresh VM. It seems to affect Cinnamon, but not MATE.

**Comment by clefebvre** [comment]
Not a solution but I'll mention a workaround in the meantime: mint-themes-legacy provides access to the original square titlebars.

**Comment by okaestne** [comment]
08ac147 fixed the close button icons in both Firefox and Thunderbird, well done :) Any ideas how to fix the borders/edges?

**Comment by OdinVex** [comment]
I think this is what `mint-themes-legacy` is for, a _sane_ option. Pretty soon we won't have borders, menus, window areas, or even a desktop at this rate. Websites are going with size 9000 fonts, titlebars are becoming 0px or 9000px in size, for the sake of progress instead of functionality. I wonder if the Linux desktops can ever unify on a set of standards to the point that a Linux clone of `WindowsBlinds` could be made to give people back whatever they want. Maybe it'd solve all problems in their own, maybe.

**Comment by mtwebster** [comment]
Patch submitted to firefox for the corner issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1746486

Workaround detailed here:
https://github.com/linuxmint/mint20.3-beta/issues/5#issuecomment-994912376
