### ISSUE TITLE
Mint-Y theme bug in 20.3 Mate edition

### ISSUE THREAD

**Issue by billyswong** [linuxmint/mint-themes#344]
![bug screencap 20220108](https://user-images.githubusercontent.com/33863356/148632531-ae790b8e-cd78-46c9-84df-3148046d47b8.png)
Context menus in Mate Panel got the highlight text color wrong.

![bug screencap 20220108b](https://user-images.githubusercontent.com/33863356/148632533-3a47060b-c226-461e-a870-118c5c2fc45a.png)
Icons in Gimp is too light (strangely the "quit" icon probably originated in system theme stays black while all others is light gray)

**Comment by clefebvre** [comment]
For Gimp, it's an issue upstream.. they call their icon theme symbolic, but they're not symbolic at all, they're monochrome. That's why they have multiple ones actually... dark and light.. 

![image](https://user-images.githubusercontent.com/1138515/148687147-40852390-4660-4a38-a74e-7de9b1326acb.png)

switch to Dark, Color or Legacy.

For the panel, I can reproduce the issue. This is something we need to fix in Mint-Y alright.

**Comment by clefebvre** [comment]
Fixed in 1.9.8.
