### ISSUE TITLE
Firefox: some legibility problems

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint-themes#356]
1) On the _Add-ons_ Firefox page, (1a) greyed-out items are excessively dim and (1b) elements in a context menu are nearly illegible:

![image](https://user-images.githubusercontent.com/47056543/150625992-3d92b477-a807-43b8-b994-3e5263454104.png)

2) On the _Themes_ Firefox page, greyed-out themes are _so_ greyed out that they are hard to see:

![image](https://user-images.githubusercontent.com/47056543/150626150-411c30fb-c077-4736-abdd-9f7f43d048f5.png)

The choice of themes within Mint seem to make no difference to any of the problems. The same goes for the choice of themes within Firefox.

Firefox ESR (91.5) has none of the problems.

Mint 20.3 Cinnamon
Firefox 96.0.1 / Mint '001 - 1.0'
I file this report against Mint only because of the new partnership that Mozilla has with Mint.

**Comment by JosephMcc** [comment]
If the choice of themes in Mint makes no difference, then this isn't an issue with mint-themes. In fact, it sounds more like an issue that should be filed with Firefox.

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc

> If the choice of themes in Mint makes no difference, then this isn't an issue with mint-themes. In fact, it sounds more like an issue that should be filed with Firefox.

Even given the partnership that I mentioned?

I think that the best way to help Mint users with this problem is for you to file a bug against Firefox. For, in my admittedly limited experience, bugs that normal users file against Firefox tend to generate little response.

**Comment by mtwebster** [comment]
No, we're not going to file firefox bugs on behalf of users, except for rare occasions where working on a bug reveals the issue is really with firefox (this was always happening, partnership or not).

It's as easy to file a bug there as it is here, and they're much better at determining if it's their issue or not. If it's not, they'll ping us or inform the original reporter to do so.

A vast majority of those themes are user-made, and it's a new theme 'engine' as of the last couple of releases, I'm sure there are issues still to work out even with the official ones.

**Comment by LinuxOnTheDesktop** [comment]
Understood. Thanks. [Done](https://bugzilla.mozilla.org/show_bug.cgi?id=1756198).
