### ISSUE TITLE
Some ideas a Windows user would like

### ISSUE THREAD

**Issue by luisrguerra** [linuxmint/mint-themes#360]
I have recently started developing an [icon theme](https://www.gnome-look.org/p/1683760) for Linux following Microsoft's Fluent Design used in Windows 11 (I believe it icon theme is the most advanced in the segment) and to have a better experience on Linux Mint I started to develop a modified version of the Mint-Y theme following the standards of Fluent Design. I think the result is getting very good and making Linux Mint very pleasant to use. I would like to share with you some of the ideas of the theme that could be applied in Linux Mint.

[Mint Wow64 Cinnamon and GTK theme](https://www.gnome-look.org/p/1683760) [(GitHub)](https://github.com/luisrguerra/mint-wow64)
[Wow64 Icon Theme](https://www.gnome-look.org/p/1614182) [(GitHub)](https://github.com/luisrguerra/wow64-icon-theme)

### Close window button in red and only showing when the mouse hover it:
![paZ3Jq5TAJ](https://user-images.githubusercontent.com/31783838/151712495-e8a28298-2822-4eb5-bc5a-c99ead16d993.gif)

### More rounded corners and fewer accent colors at calendar menu:
![JXbplSJ6cW](https://user-images.githubusercontent.com/31783838/151712497-a05870ef-3a86-4df6-ab3e-51e798b3c247.gif)

### Rounded tasks menu with glass effect and dark task bar a little more darker:
![QLT5sOZubu](https://user-images.githubusercontent.com/31783838/151712503-9974981f-1d52-4ab2-94d8-75bdc229ab83.gif)

### Glass Effect:
<img src="https://user-images.githubusercontent.com/31783838/151713502-b6100eb5-6f00-4b8b-bb9e-e08bde4c2cd1.png"  height="300" />  <img src="https://user-images.githubusercontent.com/31783838/151713504-92e3ac6c-6566-4a02-b142-b69edfc66561.png"  height="300" /> 

### Floating menu with more rounded edges, and fewer accent colors :
![ei7TE93tpk](https://user-images.githubusercontent.com/31783838/151712506-960e7957-a687-4baf-8d63-f7b86efa33ff.gif)

The input form in this style was made with box-shadow property from css simulating an outline due to css limitations on Cinnamon.

### Border contrast at Floating menu :
![Illustrator_NcIyk9KEbD](https://user-images.githubusercontent.com/31783838/151713623-43b2ab10-c95f-4f97-8f9d-490bb03bac39.png)

### Blue colors from Windows for Blue Theme (Some people don't like green as accent color at the interface and Linux Mint blue themes colors don't look good):
 #0167D5 for light backgrounds (recomended when accent color is used as background for white text)
![151713935-097fc748-0dc3-4237-a093-3544beb7be9b2](https://user-images.githubusercontent.com/31783838/151820165-3de6cefa-d6d6-4e22-b6fa-8f2fd6f92c8e.png)

#40bdff for dark backgrounds (recomended when accent color is used as background for black text)
![151713941-e913ce14-24c5-4559-aa0c-2c644a03fa2f2](https://user-images.githubusercontent.com/31783838/151820251-93fd7357-3a6b-447d-9009-67f00bdb0cfe.png)

### For the green theme could be these (I haven't had time to develop a green version yet):

#00B25A for light backgrounds (recomended when accent color is used as background for white text)
![151714079-f564855b-0afb-4480-8508-115b232e1c822](https://user-images.githubusercontent.com/31783838/151820274-d57d2d4c-45ae-43a6-9af2-d0147e3fdf0f.png)

#26FF8E for dark backgrounds (recomended when accent color is used as background for black text)
![151714080-47edccb1-a86a-453a-826a-052e8533ee844](https://user-images.githubusercontent.com/31783838/151820296-75385029-f455-4631-b987-754bad214da7.png)

**Comment by SebastJava** [comment]
> Some people don't like green as accent color at the interface and Linux Mint blue themes colors don't look good.

Oh yes ! I totally agree. I don't like this grayish-yellowish-greenish color called "Mint-Y". And I am not the only one. I can see it and feel it, just reading the forums and the web. And yes, the Mint-Y-Blue and Mint-Y-Aqua are not much better.

I am also working on this. I should take a look at your work on GitHub, but later, because I am currently totally overwhelmed by many complex things, reworking this forked `mint-themes`. I started with a new color palette, but there is much more than that going on on my computer.

You can take a look at my stuff, but please be aware that it is currently messy, as I am reworking lots of stuffs... Here : https://github.com/SebastJava/mint-yz-theme But it is really not ready, as I restarted from zero.

![image](https://user-images.githubusercontent.com/31940713/151982053-c9f84cd9-c3b8-4b18-b86a-5b28fd2488cb.png)

![Mint-Y-Variations-3](https://user-images.githubusercontent.com/31940713/151981511-7e393799-3097-40eb-b108-fc3122fa8cb6.png)

**Comment by JosephMcc** [comment]
Thanks for the suggestions. A couple of these (like less accent colors and more rounded borders in the cinnamon theme) I'll talk with the others about and see about doing down the road.
