### ISSUE TITLE
Rename src/Mint-Y/gtk-3.0 -> src/Mint-Y/gtk-3.x !?

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#390]
This is a developer issue, about a directory's name...

I guess this is not GTK version 3.0 !? I don't know... just confused here...
Then it would be less confusing to rename this directory to `src/Mint-Y/gtk-3.x` or just `src/Mint-Y/gtk-3` !?
Then all the links to this directory could be quickly updated with a single `sed` command...

**Also, is there a GTK-4 coming soon ?** Should it go into a separate `src/Mint-Y/gtk-4` ?

**Comment by JosephMcc** [comment]
There is no reason to rename this. gtk-3.0 is what it's named when the theme is created. For Gtk4 it will be gtk-4.0 just like for gtk2 it's gtk-2.0

**Comment by SebastJava** [comment]
@JosephMcc 
Can i ask you one or two simple questions, please ?

QUESTION ONE:
I am not sure, but i guess the GTK coding inside this `src/Mint-Y/gtk-3.0` is now updated to some 3.x version. Right ?
Then, for all future contributions, wouldn't it be less confusing to rename this directory to `gtk-3.x` or just `gtk-3` ?

Of course, i understand it was created with this `gtk-3.0` name, but it could be changed quickly. I could do this PR...

QUESTION TWO:
GTK-4: coming up for LM 21.0 or later ? No hurry, just asking...

Thanks.

**Comment by collinss** [comment]
'gtk-3.0' is a tag that is used internally by gtk in several places to refer to _all_ versions of gtk3. It's primary use is to distinguish it from gtk2 and gtk4. Why they chose to do that rather than simply 'gtk3' or 'gtk-3' I don't know, but if you look in /usr/share/themes/, all the other gtk themes use that naming convention - including adwaita, which is the default gnome theme. If the folder were renamed, it would probably break certain things that are specifically looking for that folder, and as @JosephMcc said, there is absolutely no reason to change it. If it helps, don't think of the 3.0 as the gtk version, but rather as the theme standards version or something similar.

**Comment by SebastJava** [comment]
Okay, understood, thanks.

**Comment by JosephMcc** [comment]
Gtk did introduce the ability to use a more specific version number for the folder at some point. For example, gtk-3.22, but that was to work around the constant breakages during the gtk3 cycle. But there is no reason for us to use it now that gtk3 is stable and we always know what we are targeting with Mint.

Gtk4 support is targeted for Mint21. I'm actually working on it right now :)
