### ISSUE TITLE
Support needed for LibAdwaita

### ISSUE THREAD

**Issue by archisman-panigrahi** [linuxmint/mint-themes#392]
Mint-Y is missing border lines for libadwaita apps. Please see the images below.

This is GNOME Clocks using adwaita.
![image](https://user-images.githubusercontent.com/3063132/179540561-a83bb54e-2e86-4f62-a279-557abe1a78f6.png)
This is blanket using adwaita.
![image](https://user-images.githubusercontent.com/3063132/179540745-7f436628-859c-4ac6-ac16-9effe712594b.png)

These are the same apps using Mint Y.
![image](https://user-images.githubusercontent.com/3063132/179541636-a598f983-9adf-49a9-986c-730cda676bac.png)
![image](https://user-images.githubusercontent.com/3063132/179541678-18fd84dc-b810-4787-a6f2-b7d2b89ad225.png)

**Comment by apandada1** [comment]
I am continuing the discussion from https://github.com/linuxmint/mint-themes/issues/391

Sorry about the delay. Now I have upgraded to Mint 21 Cinnamon.
I also could not figure out how to use Mint-Y theme with Libadwaita apps in Flatpak.

However, Blanket is available as a [PPA](https://launchpad.net/~apandada1/+archive/ubuntu/blanket/+packages) (which I maintain), and this theme can be tested without flatpak.
It would be great if Mint-Y supports horizontal lines and the accent color variable in Libadwaita.

![image](https://user-images.githubusercontent.com/3063132/183566374-9a08fc56-368b-4111-b016-541915831101.png)

**Comment by JosephMcc** [comment]
I want to follow up a bit here since we started this discussion. We were discussing the among the dev team today and I want to share at least some of my own personal thoughts. At this point I don't think there is going to be any big hurry on adding support for libadwaita. There are a few reasons for this. One of the main ideas behind it is to disallow user theming. Or at least not make it at easy as it used to be. When a dev chooses to uses it, they are basically saying they don't want us theming their app. So I'm of a mind not to. 

I've also seen comments that it will allow libadwaita devs to make changes at a more frequent pace then they can with gtk. It remains to be seen how that will bear out but if they are going to break things like the theme every 6 months the way it was happening in the gtk3 days, that will bring problems. That would mean any support we do add would only work for the version currently in Mint. And that only changes every two years.

Since I mentioned working on support at some point, I just wanted to point out where it now stands.

**Comment by apandada1** [comment]
@JosephMcc Your decision makes sense. Sadly, gtk4/libadwaita looksoutof place outside GNOME, and many developers are porting their apps to gtk4 and libadwaita, whereas gtk3 worked just fine. Although gtk4 is there, gtk3 would not become extinct anytime soon.

**Comment by JosephMcc** [comment]
Those are just my thoughts at the moment. And keep in mind that gtk4 and libadwaita aren't the same thing. You can choose to use gtk4 without libadwaita and our themes already have support for gtk4 itself.

**Comment by blue-devil-93** [comment]
The problem is that gtk4 has made a certain decision. Yes i ported Luna theme to gtk4 and it worked on gnome 40. Then came gnome 42. New libadwaita style is very different code structure if they change code this fast , you would need to bundle libadwaita with every application seperatly. Now imagine the amount of work to write an significantly  different scss/css or every application  or load a stylesheet on top of stock adwaita  that gets very buggy once adwaita changes slightly. Its pointless at the moment. Once therr are real gtk4 applications that cant be replaced its worth a try - at the moment gtk3 is more common so no real need to support libadwaita yet imho

**Comment by JoeJoeTV** [comment]
I don't mean to sound pushy but I just wanted to ask what the current state of this issue is.

Now that there is support for toggling dark mode in Linux Mint 21.2, my issues are not as big as before, but I still like my apps to look uniform ans use the theme I set and Adwaita doesn't fit that well with the rest.

So libadwaita CAN indeed be themed from what I gathered, but the Mint themes don't support it (yet), correct?
Are there any workarounds to get this working now?
And how much effort is it to add support to the Mint themes, or does libadwaita make it uneccessarily difficult to theme apps?

I don't really understand why libadwaita exists in the way it does now, because for me it just seems to make things more difficult for users. I can see how it would make developing apps easier and I also understand that app developers get issues that are just related to the broken theme they use, but it still just seems annoying. This is just my understanding though.

Also, about gtk3 being more prominent: I use lots of apps, either as flatpaks or not, that seem like they use libadwaita, mainly because the gtk3 apps don't cause any issues for me, so I think the problem has at least gotten bigger.

**Comment by archisman-panigrahi** [comment]
When installed natively (e.g. from a PPA https://launchpad.net/~apandada1/+archive/ubuntu/blanket/+packages), libadwaita apps like Blanket do work with Mint-Y after setting the environment variable `GTK_THEME=Mint-Y`. 

However, I could not find a way to theme Libadwaita apps running via Flatpak. I tried adding setting the same environment variable, but that did not work.

**Comment by JoeJoeTV** [comment]
@archisman-panigrahi Ah thanks for the info. I saw that e.g. [system-monitoring-center](https://github.com/hakandundar34coding/system-monitoring-center) used the GTK theme, if I set the `GTK_THEME` valriable when starting from the command line.

I also tried setting it globally, but that at least breaks libadwaita apps installed through flatpack, since they then use a broken version of Adwaita light with no margins at some places.

So the problem is basically getting it to work in flatpak apps. I also tried adding the environment variable AND giving the flatpak access to the themes directory, but it still doesn't work.

**Comment by archisman-panigrahi** [comment]
> So the problem is basically getting it to work in flatpak apps. I also tried adding the environment variable AND giving the flatpak access to the themes directory, but it still doesn't work.

I can confirm this issue. If Mint fixes flatpak support for libadwaita apps, and also automatically exports the variable `GTK_THEME` (not just `Mint-Y`, but the actual accent color theme choosen in system settings), then the problem will be completely solved.

**Comment by zehkira** [comment]
Flatpak apps [can't be granted permission](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) to access to directories under `/usr`. This makes it impossible for them to access the system themes.

What you *can* do is copy a theme from `/usr/share/themes` to `~/.themes` and then add a global permission for access to that directory, as well as an override for the `GTK_THEME` variable.

And there you have it - a Flatpak+Gtk4+Libadwaita app using the Mint-Y-Dark theme:

![Screenshot](https://github.com/linuxmint/mint-themes/assets/111002801/7f68d46e-9f72-4fb1-a91e-ff1588e08715)

...and as you can see, it looks quite ugly - mainly due to padding issues. Not sure if something has gone wrong here or if this is just how this theme is.

**Comment by JoeJoeTV** [comment]
> What you _can_ do is copy a theme from `/usr/share/themes` to `~/.themes` and then add a global permission for access to that directory, as well as an override for the `GTK_THEME` variable.

I can get this to work with some of my installed apps, but for e.g. Bottles it doesn't seem to change anything.

> ...and as you can see, it looks quite ugly - mainly due to padding issues. Not sure if something has gone wrong here or if this is just how this theme is.

This padding problem is also something I encountered while playing around with flatpaks and the Mint GTK themes, but mostly I saw it in combination with the default Adwaita theme, when I tried forcing an application to use an external GTK theme.
I am also now seeing this issue for some apps

**Comment by zehkira** [comment]
To summarize, the current situation is this: on a stock Mint installation, all GTK apps are themed except for the ones using Libadwaita. These can be forced to use Mint's themes, but the results don't look good.

My proposed solution is to use a `~/.config/gtk-4.0/gtk.css` file with [named colors](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/named-colors.html) to recolor Libadwaita apps. This is a much simpler and less invasive method of theming that will require little to no maintenance.

![screenshot](https://github.com/linuxmint/mint-themes/assets/111002801/cb01c11f-cd1b-4507-840d-b4f8bf134efa)

Some effort would be required to get this working:

1. Add an `/etc/skel/.config/gtk-4.0/gtk.css` file to [mintsystem](https://github.com/linuxmint/mintsystem)
2. Add `flatpak override --system --filesystem=xdg-config/gtk-4.0:ro` as an installation step
3. Create the theme and variants for all existing Mint themes
4. Make the appearance settings affect the created `gtk.css` file

**Comment by axel358** [comment]
> To summarize, the current situation is this: on a stock Mint installation, all GTK apps are themed except for the ones using Libadwaita. These can be forced to use Mint's themes, but the results don't look good.
> 
> My proposed solution is to use a `~/.config/gtk-4.0/gtk.css` file with [named colors](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/named-colors.html) to recolor Libadwaita apps. This is a much simpler and less invasive method of theming that will require little to no maintenance.
> 
> ![screenshot](https://private-user-images.githubusercontent.com/111002801/289004830-cb01c11f-cd1b-4507-840d-b4f8bf134efa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMDI0NjIsIm5iZiI6MTcxMzEwMjE2MiwicGF0aCI6Ii8xMTEwMDI4MDEvMjg5MDA0ODMwLWNiMDFjMTFmLWNkMWItNDUwNy04NDBkLWI0ZjhiZjEzNGVmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxMzQyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjJhYjExOTIxYzMzOTA5YWE1MGQ4YWQ5OTQ4YWVkNzU2N2UxYjkyYWRmZTM2MjI1MDYyY2U1ZDBjMDIxMzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OXqGw05hm667o1syjkDUR8wiBVdn8SGU5ORGBDtf-8w)
> 
> Some effort would be required to get this working:
> 
> 1. Add an `/etc/skel/.config/gtk-4.0/gtk.css` file to [mintsystem](https://github.com/linuxmint/mintsystem)
> 2. Add `flatpak override --system --filesystem=xdg-config/gtk-4.0:ro` as an installation step
> 3. Create the theme and variants for all existing Mint themes
> 4. Make the appearance settings affect the created `gtk.css` file

Problem with this is that gtk.css affects both variants, light and dark, there's no gtk-dark.css to individually theme dark apps. So u either use all apps with light colors or all apps with dark colors. My proposal is that of many to just simply add support for these widgets and let the user do the tweaking if they want, then when something breaks(wich will surely happen) they know its on them, not Mint not the apps

**Comment by archisman-panigrahi** [comment]
> libAdwaita apps are made for GNOME only and with no support for themes. 

Not really. The Arc theme and the Qogir theme work very well with libadwaita apps, for example. Even Mint-Y works decently, it just needs some configuration tweaks so that the user does not have to set everything, especially for flatpaks.

> Do not use these apps.

That is not a solution because many of these apps (e.g. Foliate, Blanket) don't have an as good alternative.

**Comment by axel358** [comment]
> libAdwaita apps are made for GNOME only and with no support for themes. They're not designed to be used in other desktops and certainly not with a theme.
> 
> Unless you're OK to use GNOME and you don't care about themes, the recommendation is pretty simple: Do not use these apps.
It's not as simple as that, mostly because because Mint itself uses GNOME apps by default, system monitor, terminal, celluloid, logs, calculator, calendar, just to name a few. For some apps is as easy as freezing them in time n patching them to build, but for how long is that sustainable?. If we had our own app ecosystem like elementary has maybe it would be as easy as staying away from libadwaita. I dont think styling things like adw action rows or preference groups as their gtk4/3/xapp equivalent would be too troublesome
