### ISSUE TITLE
Why is there no Mint-Y-Yellow theme, if there are Mint-Y-Yellow icons?

### ISSUE THREAD

**Issue by Namerif** [linuxmint/mint-themes#393]
Hi! Yesterday I was going to change the theme of my Linux Mint Cinnamon system to freshen up the look and try a new color. I started by changing Icons (I usually use the same color in Icons, Controls, and Desktop, so it looks consistent), and I really liked the Mint-Y-Yellow icons color, so I chose it. But when I proceeded to change Controls, I discovered that there is no Mint-Y-Yellow theme, even though there is a corresponding Controls theme for all other icon sets.

I find it very strange that only one specific icon set does not have a corresponding theme. Are there maybe any plans about adding this yellow theme? I would really like to try it. If not, perhaps you can give me instructions on how to make this theme myself?

**Comment by SebastJava** [comment]
This was discussed before on the LinuxMint Design Team on Slack. There is no yellow GTK theme because there is almost no contrast at all between yellow and white. Yellow is a very bright color. The foreground text for selected items is white. It is very hard to read white text on a yellow background. Check these tools for color contrasts:

https://colorable.jxnblk.com/
https://marijohannessen.github.io/color-contrast-checker/

**Take, as an extreme example, pure white on pure yellow. That's #FFFFFF on #FFFF00. That's a color contrast of 1.07. That's practically no contrast at all. Try to read this:**

![WhiteOnYellow](https://user-images.githubusercontent.com/31940713/180648257-c703383e-39f3-4183-b5b9-9cc6abfeb3a7.png)

That's practically unreadable !

Of course, we are not using pure yellow here, but still. There is no way we could get a nice yellow whit sufficient contrast. The contrast ratio should be at least 3:1, according to https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

If you want to create your own GTK theme, you could take a look at my Mint-Y fork: https://github.com/SebastJava/mint-yz-theme
There, you will find this https://github.com/SebastJava/mint-yz-theme/blob/master/Do-It-Yourself.md

**Comment by SebastJava** [comment]
P.S.: I posted this link to my fork because this [Do-It-Yourself.md](https://github.com/SebastJava/mint-yz-theme/blob/master/Do-It-Yourself.md) works for my fork only. But you can get to understand how this Mint-Y works by reading this Do-It-Yourself.

NOTE: My theme is way behind the latest updates on the Mint-Y. It is not ready for Mint 21 yet. It will probably go through messy updates before it gets ready.

**Comment by JosephMcc** [comment]
The yellow color exists for the icons because people requested it. Some people wanted a set that was essentially "folder" colored. I think the rest of you question was pretty well answered by @SebastJava
