### ISSUE TITLE
[Mint-Y Design] Please remove those dashed outlines everywhere except on the focused buttons

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint-themes#425]
```
System:
  Host: sebastien-HP-EliteDesk-800-G2-SFF Kernel: 5.15.0-58-generic x86_64
    bits: 64 Desktop: Cinnamon 5.6.7 Distro: Linux Mint 21.1 Vera
```

### Ugly distracting and meaningless outlines in Nemo and elsewhere
Here is a screenshot from the official [New Features in Linux Mint 21.1 'Vera' Cinnamon Edition - Linux Mint](https://linuxmint.com/rel_vera_cinnamon_whatsnew.php):

![New-look-still-needs-improvements](https://user-images.githubusercontent.com/31940713/213429596-ace1ce96-9814-4874-8520-23e7fd6ee6ec.png)

That's great news ! Much better colors, and no more darkening on the selected icons. But what's that dashed outline, there, on the "Desktop" directory name? What is this supposed to mean? Is it useful? I never understood this... I think i don't need this information, and those dashed outlines are ugly and distracting.

I understand this is needed to show the focus on the buttons, but in most other cases it is irrelevant or unneeded.

### To Reproduce
**There are various cases.** In Nemo and elsewhere. One common and simple example happens when you delete one item in Nemo.

1. Select Mint-Y GTK theme.
2. Open Nemo in icon view.
3. Delete one file or directory.
4. See: the next item gets a dashed outline on its name. That's irrelevant and distracting information.
5. Undo deletion.
6. See: the next item still gets a dashed outline on its name. That's irrelevant and distracting information.

### Video capture in Nemo

https://user-images.githubusercontent.com/31940713/213436048-8b92d127-9780-4489-923d-d97c5b1a66b9.mp4

### Additional context
Sorry to insist. We already talked about this, a long time ago. But at the time i did not clearly specify we could keep the outlines on the buttons, and just get rid of it where it is not really needed: everywhere else.

This dashed outline still doesn't look nice, but at least we got rid of it where it was irrelevant.

### Method
1. In `src/Mint-Y/gtk-3.0/sass/_common.scss`, search for `outline-style: dashed;` and replace with `outline-style: none;`
2. In the general button styling, starting with `// Buttons` currently on line 311, more precisely, under `button {` (currently on line 335), add `outline-style: dashed;`
3. Build and test.

**Example:**
```
button {
  min-height: 22px;
  min-width: 20px;
  transition: $button_transition;
  border: 1px solid;
  border-radius: 3px;
  padding: 5px 8px;
  outline-style: dashed;
```

**Comment by SebastJava** [comment]
I already made this years ago, on my old fork. It works. I only had to change to lines in `src/Mint-Y/gtk-3.0/sass/_common.scss`.

**Comment by JosephMcc** [comment]
> Sorry to insist. We already talked about this, a long time ago. But at the time i did not clearly specify we could keep the outlines on the buttons, and just get rid of it where it is not really needed: everywhere else.

If you feel sorry, then maybe you shouldn't insist. Just because you find something irrelevant doesn't mean that everyone does. Those focus lines exist for people who use the keyboard almost exclusively for navigation. And believe me there are a lot. Mint-X doesn't support these very well and it was constantly complained about. These actually serve a purpose to a lot of users weather you like them or not. A lot of people would be very frustrated if they were removed from everywhere except buttons.

**Comment by SebastJava** [comment]
"Sorry", in this case, was just about being polite. But if you clearly state that i am bothering you, then okay, i will stop. At least. I'll try to make my reply short:

* I can't find many cases where those outlines are useful. Except for buttons, of course. In Nemo, they just look erratic, to me.
* In GTK-4, they are still there, everywhere, bothering me, but at least, they disappear after approx. 5 seconds. That's better.

**Comment by JosephMcc** [comment]
> I can't find many cases where those outlines are useful. Except for buttons, of course. In Nemo, they just look erratic, to me.

This is where the misunderstanding is. They look erratic to you. But if you are using the arrow keys to navigate, they indicate what item you are currently on. So if I'm using the keyboard arrows to navigate, I'll know where I'll be going next. Or if I hit enter, I know that is the folder I will be diving into. A lot of people work this way. Removing those from everything but buttons would break the workflow of a lot of users. You have to keep in mind that just because you use a heavily mouse centeric workflow, not everyone does.
