### ISSUE TITLE
Make Linux Mint cinnamon theme flatter.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint-themes#431]
The Linux Mint cinnamon theme that comes with the Mint-X theme would be good to rebase on the Mint-Y theme, in case the user wants to use other gtk themes.

**Comment by luisrguerra** [comment]
I think the Mint-X theme is kept just for nostalgia. In my opinion it should be discontinued as it is unsuitable for modern UI design concepts.

**Comment by AxelKelo** [comment]
It's the only consistent and updated skeuomorphic gtk theme left nowadays. It would be barbaric to abandon it, or make it the same as all the others primitive flattened designs. There are already enough of those! People should have a choice

**Comment by mfreeman72** [comment]
Oh, please no!!! Do NOT remove Mint-X! That's the only good theme out there any more! I absolutely HATE this nasty, ugly, boring flat trend. Give me some contour and shading, please! Even just drop shadows behind buttons would be better than the totally flat junk out there now. Don't flatten everything like every other stupid OS out there! Flat = ugly and non-workable for me. Maybe I'm just old, but I lived through the days when everything was flat out of necessity. Now it's flat again, but by design, for some insane reason, and I just don't get why anyone would think that's a good thing.
