### ISSUE TITLE
Theme inconsistency between XApp applets and normal applets

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint-themes#443]
## Issue

There is a theme inconsistency between the menus from the status icons in the **xapp-status** applet and **normal applets** in the panel. This seems to be happening since the menus in the xapp-status applet are themed following the applications theme and other applets in the panel are themed using the desktop theme.

### Exemplification

If by example I choose a light theme for the applications and a dark one for the desktop the result would be as shown below:

- For apps in the **xapp-status** applet:

![Screenshot from 2023-05-06 22-56-28](https://user-images.githubusercontent.com/63073056/236651322-eef36dda-f9f6-4cde-a119-f58a06f5fc54.png)

- For **normal applets**:

![Screenshot from 2023-05-06 23-09-53](https://user-images.githubusercontent.com/63073056/236651324-b30264ef-9321-4d8e-b321-14b28b21ff60.png)

### Additional Information

I am not completely sure but the icons in the xapp-status applet seem to have (a bit) less space between each other than the other applets do.

### Solution

If this behavior is not required for the xapp-status to work through the different distributions you support, then the menus in the xapp-status applets should all follow the theming from the desktop, as other applets do, to maintain a greater level of consistency of the themes through the system.

**P.S.** I am not sure if this is the best repository for this issue, so feel free to reallocate to a more adequate one.

**Comment by JosephMcc** [comment]
This happens because two different toolkits are being used to render them as you noticed. The menus from status icons are GtkMenu's so get different theming. Don't think there is much that can really be done about this.

**Comment by anaximeno** [comment]
> This happens because two different toolkits are being used to render them as you noticed. The menus from status icons are GtkMenu's so get different theming. Don't think there is much that can really be done about this. 

Sure, I'll keep this issue open for reference (if someone notices the same issue), if you do don't mind.

**Comment by mfreeman72** [comment]
There used to be a setting in Cinnamon that would fix this. I forget exactly what it was called, but I think it would use Ubuntu/Gnome's indicator applet format menus instead of standard gtkmenu. This made it blend in better with Cinnamon applets. It also caused some issue, apparently. I never saw any problems, personally, but it was removed because of this. I personally miss that, and wish they would bring that back, since it was optional anyway, because it makes my desktop feel somehow unfinished or unprofessional when applet menu styles are so inconsistent and weird, especially when they're right next to each other on the panel. If that can't be brought back, then I wish there was something else that could be done about this. Like if there was some way to intercept the menu contents of the gtkmenus and have the applet displaying them interpret them into something that matches the panel theme. I'm not sure how possible that is, though. In any case, it sure is ugly the way things are now.

**Comment by JosephMcc** [comment]
Just for reference what @mfreeman72 is referring to is something that was a broken/buggy mess internally. It's also something you will probably never see coming back unless someone comes up with a much better way of doing it. Unfortunately dealing with those types of status applets that live in the panel is a mess of different standards. That's a large part of the reason that the xapp status applet thing was created. So Mint had some kind of consistency and control over how these worked in MInt.

Going to close this. Everyone may not like the answer but it isn't a bug and there is currently no real solution to making it better.
